"""Updated reviews2

Revision ID: 64be5a4ed913
Revises: 22ca85a8311a
Create Date: 2024-01-27 09:26:57.938742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64be5a4ed913'
down_revision = '22ca85a8311a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_review_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('fk_review_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
